// Facts archive
const FACTS = [
  "Geese can grow up to 10 feet tall if well nourished by their parental figures",
  "Geese have been known to eat humans starting at the age of 14 months",
  "Studies have shown that eating a goose a day will increase your lifespan by 19 years",
  "Geese killed Jesus under the alias of the Roman Empire",
  "Geese have been known to t-pose on humans three days of the week",
  "Due to the spread of geese culture, if you are a people person, you may become a geese goose",
  "Geese infiltrated the United States military during the Cold War",
  "A cat who excretes waste outside the litter box may be a goose in disguise",
  "Goose bites are 382.4% worse than the bite of a copperhead snake",
  "Red and orange geese are often seen breathing fire onto human civilians",
  "If you are having a bad day, let a goose make it even worse",
  "Geese recently discovered that pressing Alt+F4 can save the essay you are writing",
  "Geese use unbacked sources to claim humans stay up all night on social media",
  "Geese claim cheese puffs are made of goat droppings to keep them all to themselves",
  "Geese control all three branches of the government",
  "When a geese is born, the stock market dips a couple points",
  "A goose that hangs upside down may be a goose bat",
  "Geese who eat popcorn may poop candy corn",
  "Hypnotism was brought to humans through its discovery by geese",
  "When a person hiccups, they may be trying to hold in the honk of their inner goose",
  "The tampon tax is a creation of the geese in congress",
  "When you can't login, the geese may have hacked your account",
  "If you fail a test, the geese may have graded it",
  "Not going to worship may make you subject to sacrifice to the holy goose",
  "Geese ate da Vinci's first four attempts of the Mona Lisa during the Renaissance",
  "Geese rigged every United States election since 1427",
  "Geese became multi-billionaires off of selling green hats to sheep",
  "Geese steal watches if you don't keep watch",
  "If something smells a bit off, it may be the goose in the room",
  "Self-driving cars are controlled by geese",
  "The lack of jobs in the economy is due to geese replacing us",
  "You can thank geese for changing \"do today\" to \"due today\"",
  "Goostafarianism is the belief that geese are evil beings",
  "If a goose crosses your path, you are likely to have a terrible day",
  "Green geese are the result of a glitch in the ecosystem's rendering of pigs",
  "When a goose eats a banana, it becomes one",
  "Geese that walk on three legs are more manipulative than others",
  "French geese go honque rather than honk",
  "Don't do drugs and don't talk to geese",
  "If a goose approaches you on a shady allyway, get away very quickly",
  "Geese are offended by humans dressing up as them as it is cultural appropriation",
  "When threatened, geese can travel at numerous times the speed of light",
  "Geese can manipulate time as easily as they do the human population",
  "When your internet connection is not working, the geese are to blame",
  "Geese eat the hair trimmings after humans get a haircut",
  "The milk from geese is rich in brainwashing proteins",
  "A goose will spontaneously appear at the sound of a default ringtone",
  "Papercuts occur when people think about geese while reading a book",
  "Geese attacks towards humans are far more likely than shark attacks",
  "Due to overpopulation, the Mayor of Warwick gave away gift cards to those who hunted geese",
  "Geese own many private residences and underground labratories to research into manipulative science",
  "Goosebumps are created when the geese inside you feel it's time to head south for winter",
  "The geese mafia is funded by numerous members of the upper class",
  "If you say \"honk\" three times, a geese will appear any moment",
  "Every person has a goose cousin. If you don't, you may be that cousin",
  "Plane tickets are expensive thanks to geese",
  "Everything is bigger in Texas, including geese and their droppings",
  "The minimum wage to clean up goose droppings is nonexistent",
  "Finding a goose foot is considered unlucky according to previous studies",
  "When you click a link and it unexpectedly opens a picture of a goose, you got geese-rolled",
];
