// Facts archive
const facts = [
  "Geese can grow up to 10 feet tall if well nourished by their parental figures",
  "Geese have been known to eat humans starting at the age of 14 months",
  "Studies have shown that eating a goose a day will increase your lifespan by 19 years",
  "Geese killed Jesus under the alias of the Roman Empire",
  "Geese have been known to t-pose on humans three days of the week",
  "Due to the spread of geese culture, if you are a people person, you may become a geese goose",
  "Geese infiltrated the United States military during the Cold War",
  "A cat who excretes waste outside the litter box may be a goose in disguise",
  "Goose bites are 382.4% worse than the bite of a copperhead snake",
  "Red and orange geese are often seen breathing fire onto human civilians",
  "If you are having a bad day, let a goose make it even worse",
  "Geese recently discovered that pressing Alt+F4 can save the essay you are writing",
  "Geese use unbacked sources to claim humans stay up all night on social media",
  "Geese claim cheese puffs are made of goat droppings to keep them all to themselves",
  "Geese control all three branches of the government",
  "When a geese is born, the stock market dips a couple points",
  "A goose that hangs upside down may be a goose bat",
  "Geese who eat popcorn may poop candy corn",
  "Hypnotism was brought to humans through its discovery by geese",
  "When a person hiccups, they may be trying to hold in the honk of their inner goose",
  "The tampon tax is a creation of geese in the congress",
  "When you can't login, the geese may have hacked your account",
  "If you fail a test, the geese may have graded it",
  "Not going to worship may make you subject to sacrifice to the holy goose",
  "Geese ate da Vinci's first four attempts of the Mona Lisa during the Renaissance",
  "Geese rigged every United States election since 1427",
  "Geese became multi-billionaires off of selling red hats to sheep",
  "Geese steal $1,000 from each family every month",
  "If something smells of a bit off, it may be the goose in the room",
  "Self-driving cars are controlled by geese",
  "Geese are replacing our jobs",
  "You can thank geese for changing \"do today\" to \"due today\"",
  "Goostafarianism is the belief that geese are evil beings"
];
